### ISSUE TITLE
Not figuring out how to get a JSON.parse error to be propagated through the pull stream flow

### ISSUE THREAD

**Issue by daviddias** [diasdavid/pull-ndjson#1]
@dignifiedquire any tips? I would like to understand this better.

Test: https://github.com/diasdavid/pull-ndjson/blob/master/test/ndjson.spec.js#L43-L55

**Comment by dignifiedquire** [comment]
It looks like `pull-split` doesn't do proper error handling currently. This could be fixed by replacing https://github.com/pull-stream/pull-split/blob/master/index.js#L12 with

``` js
try {
  piece = mapper(piece)
} catch (err) {
  return stream.emit('error', err)
}
```

**Comment by ahdinosaur** [comment]
hey y'all, :smile_cat: 

[here's](https://github.com/ahdinosaur/pull-json-doubleline/blob/v2/index.js#L16-L22) how i did it in a [pending re-write of `pull-json-doubleline`](https://github.com/dominictarr/pull-json-doubleline/pull/1), a very similar module to this one:

``` js
function parse () {
  return pull(
    split('\n\n'),
    pull.filter(), // filter empty lines
    pull.map(JSON.parse)
  )
}
```

the reason was [`pull.map` already does a `try` / `catch`](https://github.com/pull-stream/pull-stream/blob/master/throughs/map.js#L12-L18) and i would rather `pull-split` be only focused on splitting, not also on doing a mapping.
